import { useState, useEffect } from "react";
import DashboardLayout from "../components/DashboardLayout";
import {
  Box, Typography, Button, Card, CardContent, Grid,
  Stack, Avatar, useTheme, Chip, CircularProgress,
  IconButton, Tooltip
} from "@mui/material";
import DescriptionIcon from "@mui/icons-material/DescriptionRounded";
import DownloadIcon from "@mui/icons-material/DownloadRounded";
import FavoriteIcon from "@mui/icons-material/FavoriteRounded";
import WaterDropIcon from "@mui/icons-material/WaterDropRounded";
import ScienceIcon from "@mui/icons-material/ScienceRounded";
import HistoryIcon from "@mui/icons-material/HistoryRounded";
import VisibilityIcon from "@mui/icons-material/VisibilityRounded";
import { motion, AnimatePresence } from "framer-motion";
import { api } from "../api/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const theme = useTheme();

  const fetchReports = () => {
    setLoading(true);
    api.get("/cases")
      .then(res => {
        console.log("Reports data fetched:", res.data);
        if (Array.isArray(res.data)) setReports(res.data);
        else setError("Data format error");
      })
      .catch(err => {
        console.error("Failed to load reports:", err);
        setError(err.message || "Connection failed");
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const getIcon = (type) => {
    switch (type) {
      case "HEART": return <FavoriteIcon />;
      case "DIABETES": return <WaterDropIcon />;
      case "LIVER": return <ScienceIcon />;
      case "ECG": return <FavoriteIcon />;
      default: return <DescriptionIcon />;
    }
  };

  const downloadReport = (report) => {
    const doc = new jsPDF();
    let predictions = [];
    try {
      predictions = typeof report.predictions === 'string'
        ? JSON.parse(report.predictions)
        : report.predictions || [];
    } catch (e) {
      console.error(e);
    }

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("MedHive Medical Report", 20, 30);

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 40);
    doc.text(`Report ID: ${report.id}`, 20, 45);

    // Patient Info
    doc.setDrawColor(200);
    doc.line(20, 55, 190, 55);
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Case Information", 20, 65);

    doc.setFontSize(11);
    doc.text(`Patient Name: ${report.patient_name || 'N/A'}`, 20, 75);
    doc.text(`Analysis Type: ${report.type}`, 20, 82);
    doc.text(`Status: ${report.priority}`, 20, 89);
    doc.text(`Recorded At: ${new Date(report.created_at).toLocaleString()}`, 20, 96);

    // Results Table
    doc.setFontSize(14);
    doc.text("Analysis Results", 20, 110);

    const tableData = [[
      predictions[0]?.label || predictions[0]?.disease || "N/A",
      `${report.risk_score}%`,
      report.priority
    ]];

    autoTable(doc, {
      startY: 115,
      head: [['Prediction Label', 'Confidence/Risk', 'Priority Status']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillStyle: [41, 128, 185] }
    });

    // Disclaimer
    const finalY = (doc).lastAutoTable.finalY || 130;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("DISCLAIMER: This report is generated by AI and intended for informational purposes only.", 20, finalY + 20);
    doc.text("Please consult a qualified medical professional for diagnosis and treatment.", 20, finalY + 25);

    doc.save(`${report.type}_Report_${report.id}.pdf`);
  };

  const downloadAllReports = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("MedHive Consolidated Medical History", 20, 20);

    const tableBody = reports.map(r => {
      let pred = [];
      try { pred = typeof r.predictions === 'string' ? JSON.parse(r.predictions) : r.predictions || []; } catch (e) { }
      return [
        new Date(r.created_at).toLocaleDateString(),
        r.type,
        pred[0]?.label || pred[0]?.disease || "N/A",
        `${r.risk_score}%`,
        r.priority
      ];
    });

    autoTable(doc, {
      startY: 30,
      head: [['Date', 'Type', 'Result', 'Confidence', 'Priority']],
      body: tableBody,
    });

    doc.save("MedHive_Complete_Reports.pdf");
  };

  const getColor = (type) => {
    switch (type) {
      case "HEART": return theme.palette.error.main;
      case "DIABETES": return theme.palette.primary.main;
      case "LIVER": return theme.palette.success.main;
      case "ECG": return theme.palette.warning.main;
      default: return theme.palette.grey[500];
    }
  };

  return (
    <DashboardLayout>
      <Box sx={{ mb: 4, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
          <DescriptionIcon sx={{ fontSize: 40, color: "primary.main" }} />
          <Box>
            <Typography variant="h4" fontWeight={900}>
              Medical Reports
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Centralized hub for all your analyzed scan results
            </Typography>
          </Box>
        </Box>
        <Stack direction="row" spacing={2}>
          <Button
            variant="outlined"
            startIcon={<HistoryIcon />}
            onClick={fetchReports}
            sx={{ borderRadius: 3, fontWeight: 700 }}
          >
            Refresh
          </Button>
          <Button
            variant="contained"
            startIcon={<DownloadIcon />}
            onClick={downloadAllReports}
            sx={{ borderRadius: 3, py: 1, px: 3, fontWeight: 700 }}
            disabled={reports.length === 0}
          >
            Download All
          </Button>
        </Stack>
      </Box>

      {loading ? (
        <Box sx={{ display: "flex", justifyContent: "center", py: 10 }}>
          <CircularProgress size={60} thickness={4} />
        </Box>
      ) : error ? (
        <Card sx={{ borderRadius: 4, bgcolor: "rgba(211, 47, 47, 0.05)", border: '1px solid', borderColor: 'error.main' }}>
          <CardContent sx={{ py: 6, textAlign: 'center' }}>
            <Typography variant="h6" fontWeight={700} color="error.main">Error Loading Reports</Typography>
            <Typography variant="body2" color="text.secondary">{error}</Typography>
            <Button onClick={fetchReports} sx={{ mt: 2 }} color="error" variant="contained">Try Again</Button>
          </CardContent>
        </Card>
      ) : reports.length === 0 ? (
        <Card sx={{ borderRadius: 4, bgcolor: "background.paper", border: '1px dashed', borderColor: 'divider' }}>
          <CardContent sx={{ py: 10 }}>
            <Stack spacing={2} alignItems="center">
              <DescriptionIcon sx={{ fontSize: 100, color: "text.secondary", opacity: 0.1 }} />
              <Typography variant="h6" fontWeight={700} color="text.secondary">
                No reports generated yet
              </Typography>
              <Typography variant="body2" color="text.secondary" align="center" sx={{ maxWidth: 300 }}>
                Reports will appear here once you complete a Heart, Diabetes, or ECG analysis.
              </Typography>
              <Button onClick={fetchReports} variant="text">Check Again</Button>
            </Stack>
          </CardContent>
        </Card>
      ) : (
        <Grid container spacing={3}>
          <AnimatePresence>
            {reports.map((report, index) => {
              let parsedPredictions = [];
              try {
                parsedPredictions = typeof report.predictions === 'string'
                  ? JSON.parse(report.predictions)
                  : report.predictions || [];
              } catch (e) {
                console.error("Failed to parse predictions", e);
              }

              return (
                <Grid item xs={12} sm={6} md={4} key={report.id}>
                  <motion.div
                    initial={{ opacity: 0, scale: 0.9, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                  >
                    <Card sx={{
                      borderRadius: 4,
                      border: '1px solid',
                      borderColor: 'divider',
                      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                      '&:hover': {
                        transform: 'translateY(-8px)',
                        boxShadow: '0 12px 40px rgba(0,0,0,0.08)',
                        borderColor: 'primary.main'
                      }
                    }}>
                      <CardContent sx={{ p: 3 }}>
                        <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                          <Avatar sx={{ bgcolor: `${getColor(report.type)}15`, color: getColor(report.type), width: 50, height: 50 }}>
                            {getIcon(report.type)}
                          </Avatar>
                          <Chip
                            label={report.priority}
                            size="small"
                            color={report.priority === "HIGH" ? "error" : "success"}
                            sx={{ fontWeight: 800, borderRadius: 1.5 }}
                          />
                        </Box>

                        <Typography variant="h6" fontWeight={800} gutterBottom>
                          {report.type} Report
                        </Typography>

                        <Typography variant="body2" color="text.secondary" fontWeight={500} sx={{ mb: 2, display: 'flex', alignItems: 'center', gap: 0.5 }}>
                          <HistoryIcon sx={{ fontSize: 16 }} /> {new Date(report.created_at).toLocaleString()}
                        </Typography>

                        <Box sx={{ p: 1.5, bgcolor: 'rgba(0,0,0,0.02)', borderRadius: 2, mb: 2, border: '1px solid rgba(0,0,0,0.04)' }}>
                          <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 0.5 }}>
                            Analysis Result
                          </Typography>
                          <Typography variant="body2" fontWeight={700}>
                            {Array.isArray(parsedPredictions) && parsedPredictions[0]
                              ? (parsedPredictions[0].label || parsedPredictions[0].disease || "Completed")
                              : "Review Analysis"
                            }
                          </Typography>
                        </Box>

                        <Box sx={{ display: 'flex', gap: 1 }}>
                          <Button
                            fullWidth
                            variant="outlined"
                            startIcon={<VisibilityIcon />}
                            sx={{ borderRadius: 2, fontWeight: 700 }}
                          >
                            View
                          </Button>
                          <Tooltip title="Download PDF">
                            <IconButton
                              onClick={() => downloadReport(report)}
                              sx={{
                                bgcolor: 'primary.main',
                                color: 'white',
                                borderRadius: 2,
                                '&:hover': { bgcolor: 'primary.dark' }
                              }}
                            >
                              <DownloadIcon fontSize="small" />
                            </IconButton>
                          </Tooltip>
                        </Box>
                      </CardContent>
                    </Card>
                  </motion.div>
                </Grid>
              );
            })}
          </AnimatePresence>
        </Grid>
      )}
    </DashboardLayout>
  );
}
